name: trendiq
description: ""
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  logger: ^2.6.1
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.8
  get: ^4.7.2
  flutter_bloc: ^9.1.1
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
  hydrated_bloc: ^10.0.0
  carousel_slider: ^5.1.1
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  skeletonizer: ^2.0.1
  toastification: ^3.0.3
  firebase_auth: ^5.6.1
  google_sign_in: ^7.0.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_stripe: ^11.5.0
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-ExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
